- name: verify
  hosts: all
  become: true
  tasks:
    - name: Run 'nvme --list' and capture the output
      ansible.builtin.command: nvme --list
      args:
        chdir: "/tmp/"
      when: inventory_hostname in groups['all']
      register: firmware_version_output

    - name: Parse firmware version
      set_fact:
        firmware_version: "{{ firmware_version_output.stdout | regex_search('FW Rev\\s+(\\S+)', '\\1') }}"

    - name: Check if firmware version matches
      fail:
        msg: "Server firmware version is not 5B2QGXA7"
      when: firmware_version != "5B2QGXA7"

    - name: Server upgraded to 5B2QGXA7
      debug:
        msg: "Server upgraded to 5B2QGXA7"
      when: firmware_version == "5B2QGXA7"

    - name: Check firmware version
      ansible.builtin.command: "nvme --list"
      args:
        chdir: "/tmp/"
      when: inventory_hostname in groups['all']
      register: firmware_version_output
