---
- name: Reboot servers one by one
  hosts: all
  serial: 1  
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 300
      async: 120
      poll: 0
      become: yes

    - name: Reboot
      ansible.builtin.reboot: reboot_timeout=600
      become: true

    - name: Ping Connection
      ansible.builtin.ping:    

    - name: start the service
      systemd:
        name: mysql
        state: started

- name: Final tasks
  hosts: all
  tasks:
    - name: Perform final tasks
      debug:
        msg: "Server {{ inventory_hostname }} is up and can be accessed."

