---
- name: Download Samsung SSD firmware and perform actions
  hosts: all
  become: true
  serial: 
    1
  tasks:
    - name: Set the HTTPS proxy
      ansible.builtin.shell: export https_proxy=http://pkg.proxy.prod.jp.local:10080
      environment:
        https_proxy: http://pkg.proxy.prod.jp.local:10080
      register: set_proxy
      changed_when: false 

    - name: Download Samsung SSD firmware ISO
      ansible.builtin.get_url:
        url: https://semiconductor.samsung.com/resources/software-resources/Samsung_SSD_980_PRO_5B2QGXA7.iso
        dest: /tmp/Samsung_SSD_980_PRO_5B2QGXA7.iso

    - name: Create firmware directory
      ansible.builtin.file:
        path: /tmp/Samsung_SSD_980_PRO_firmware
        state: directory

    - name: Mount ISO
      ansible.builtin.mount:
        src: /path/to/Samsung_SSD_980_PRO_5B2QGXA7.iso
        path: /path/to/Samsung_SSD_980_PRO_firmware
        fstype: iso9660
        state: mounted

    - name: Create _temp_dir directory
      ansible.builtin.file:
        path: /tmp/_temp_dir
        state: directory

    - name: Copy initrd
      ansible.builtin.copy:
        src: /tmp/Samsung_SSD_980_PRO_firmware/initrd
        dest: /tmp/_temp_dir/initrd

    - name: Extract initrd
      ansible.builtin.command: zcat initrd | cpio -i -c
      args:
        chdir: /tmp/_temp_dir

    - name: Install unzip using yum
      ansible.builtin.yum:
        name: unzip
        state: present

    - name: Run fumagician
      ansible.builtin.command: root/fumagician/fumagician 2> root/fumagician/log
      args:
        chdir: /tmp/_temp_dir

