---
- name: Reboot servers one by one
  hosts: all
  serial: 1  
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 120
      async: 120
      poll: 0
      become: yes

    - name: Wait for server's sshd to start
      local_action:
        wait_for port="22" host="{{ ansible_host }}" search_regex="OpenSSH" delay=60


- name: Final tasks
  hosts: all
  tasks:
    - name: Perform final tasks
      debug:
        msg: "Server {{ inventory_hostname }} is up and can be accessed."

