---
- name: Reboot servers one by one
  hosts: all
  serial: 1  
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 300
      async: 120
      poll: 0
      become: yes

    - name: ping the server
      ansible.builtin.ping:    

    - name: create a new file to test
      ansible.builtin.command: "touch ansible_test"

- name: Final tasks
  hosts: all
  tasks:
    - name: Perform final tasks
      debug:
        msg: "Server {{ inventory_hostname }} is up and can be accessed."

